<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgroTech.BLL\AgroTech.BLL.csproj" />
  </ItemGroup>

</Project>
